FROM python:3.10-slim

WORKDIR /app

COPY ./app/requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt

COPY ./app ./

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
